### ISSUE TITLE
ERROR: Unable to find the resource: /META-INF/BenchmarkList

### ISSUE THREAD

**Issue by wangyiran126** [artyushov/idea-jmh-plugin#22]
i user intellj jmh plugin,and use sbt to mange the dependency,i cannot use maven, because play2 framework not support maven just sbt.
the error 
Exception in thread "main" java.lang.RuntimeException: ERROR: Unable to find the resource: /META-INF/BenchmarkList
	at org.openjdk.jmh.runner.AbstractResourceReader.getReaders(AbstractResourceReader.java:97)
	at org.openjdk.jmh.runner.BenchmarkList.find(BenchmarkList.java:103)
	at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:256)
	at org.openjdk.jmh.runner.Runner.run(Runner.java:206)
	at org.openjdk.jmh.Main.main(Main.java:71)

**Comment by wangyiran126** [comment]
i add libraryDependencies += "org.openjdk.jmh" % "jmh-generator-annprocess" % "1.15",and invalidate cache in intellij,the program solved

**Comment by stokito** [comment]
may be related to #13

**Comment by andyczerwonka** [comment]
I'm now getting this recently... I came back to an existing project and am now seeing everything
